#pragma once

#include <string>
#include <utility>

/*
 * Model for users table defined as:
 * users
 * (
 *     user_id bigint primary key generated by default as identity,
 *     email varchar(64) not null,
 *     password varchar(76) not null,
 *     first_name varchar(32) not null,
 *     last_name varchar(32) not null,
 *     created_at timestamp without time zone default (now() at time zone 'utc'),
 *     modified_at timestamp without time zone default (now() at time zone 'utc')
 * );
 */
class User
{
public:
    User() = default;
    User(User const&) = default;
    User& operator=(User const&) = default;
    User(User&&) noexcept = default;
    User& operator=(User&&) noexcept = default;

    /**
     * Constructor for all User parameters.
     * @param userId User ID.
     * @param email User email.
     * @param password User password (hashed).
     * @param firstName User first name.
     * @param lastName User last name.
     * @param createdAt When the user was created.
     * @param modifiedAt When the user was last updated.
     */
    User
    (
        uint64_t const userId,
        std::string email,
        std::string password,
        std::string firstName,
        std::string lastName,
        uint64_t const createdAt,
        uint64_t const modifiedAt
    )
    : m_email(std::move(email))
    , m_password(std::move(password))
    , m_firstName(std::move(firstName))
    , m_lastName(std::move(lastName))
    , m_userId(userId)
    , m_createdAt(createdAt)
    , m_modifiedAt(modifiedAt)
    {}

    /**
     * Constructor for saving a user.
     * userId, createdAt and modifiedAt are generated by the database.
     * @param email User email.
     * @param password User password (hashed).
     * @param firstName User first name.
     * @param lastName User last name.
     */
    User
    (
        std::string email,
        std::string password,
        std::string firstName,
        std::string lastName
    )
    : m_email(std::move(email))
    , m_password(std::move(password))
    , m_firstName(std::move(firstName))
    , m_lastName(std::move(lastName))
    {}

    [[maybe_unused]] [[nodiscard]] uint64_t getUserId() const
    {
        return m_userId;
    }

    [[maybe_unused]] void setUserId(uint64_t uid)
    {
        m_userId = uid;
    }

    [[maybe_unused]] [[nodiscard]] std::string getEmail() const
    {
        return m_email;
    }

    [[maybe_unused]] void setEmail(std::string email)
    {
        m_email = std::move(email);
    }

    [[maybe_unused]] [[nodiscard]] std::string getPassword() const
    {
        return m_password;
    }

    [[maybe_unused]] void setPassword(std::string password)
    {
        m_password = std::move(password);
    }

    [[maybe_unused]] [[nodiscard]] std::string getFirstName() const
    {
        return m_firstName;
    }

    [[maybe_unused]] void setFirstName(std::string firstName)
    {
        m_firstName = std::move(firstName);
    }

    [[maybe_unused]] [[nodiscard]] std::string getLastName() const
    {
        return m_lastName;
    }

    [[maybe_unused]] void setLastName(std::string lastName)
    {
        m_lastName = std::move(lastName);
    }

    [[maybe_unused]] [[nodiscard]] uint64_t getCreatedAt() const
    {
        return m_createdAt;
    }

    [[maybe_unused]] void setCreatedAt(uint64_t createdAt)
    {
        m_createdAt = createdAt;
    }

    [[maybe_unused]] [[nodiscard]] uint64_t getModifiedAt() const
    {
        return m_modifiedAt;
    }

    [[maybe_unused]] void setModifiedAt(uint64_t modifiedAt)
    {
        m_modifiedAt = modifiedAt;
    }

private:
    std::string m_email{};
    std::string m_password{};
    std::string m_firstName{};
    std::string m_lastName{};
    uint64_t m_userId{};
    uint64_t m_createdAt{};
    uint64_t m_modifiedAt{};
};
